Added delaycompress and better log protection

diff --git a/playbooks/roles/os-log-centralizer/files/logshipper b/playbooks/roles/os-log-centralizer/files/logshipper
--- a/playbooks/roles/os-log-centralizer/files/logshipper
+++ b/playbooks/roles/os-log-centralizer/files/logshipper
@@ -29,6 +29,12 @@ then
    for file in $(ls . | egrep '*.log[0-9]{10,20}')
    do
      /usr/local/bin/openstack object create openstack-logs $file &> /var/log/logshipper.log
+     if [ "$?" != "0" ]
+     then
+       echo "$(date +%F'-'%T) Upload of $file failed. Moving to /var/log/uploadfail..."
+       mkdir -p /var/log/uploadfail
+       cp $file /var/log/uploadfail
+     fi
    done
 fi
 
@@ -43,6 +49,12 @@ then
    for file in $(ls . | egrep '*.log[0-9]{10,20}')
    do
      /usr/local/bin/openstack object create infrastructure-logs $file &> /var/log/logshipper.log
+     if [ "$?" != "0" ]
+     then
+       echo "$(date +%F'-'%T) Upload of $file failed. Moving to /var/log/uploadfail..."
+       mkdir -p /var/log/uploadfail
+       cp $file /var/log/uploadfail
+     fi   
    done
 fi
 
@@ -57,6 +69,12 @@ then
    for file in $(ls . | egrep '*.log[0-9]{10,20}')
    do
      /usr/local/bin/openstack object create operatingsystem-logs $file &> /var/log/logshipper.log
+     if [ "$?" != "0" ]
+     then
+       echo "$(date +%F'-'%T) Upload of $file failed. Moving to /var/log/uploadfail..."
+       mkdir -p /var/log/uploadfail
+       cp $file /var/log/uploadfail
+     fi
    done
 fi
 
@@ -71,6 +89,12 @@ then
    for file in $(ls . | egrep '*.log[0-9]{10,20}')
    do
      /usr/local/bin/openstack object create networkgear-logs $file &> /var/log/logshipper.log
+     if [ "$?" != "0" ]
+     then
+       echo "$(date +%F'-'%T) Upload of $file failed. Moving to /var/log/uploadfail..."
+       mkdir -p /var/log/uploadfail
+       cp $file /var/log/uploadfail
+     fi  
    done
 fi
 
